version: '3'
services:
  build-port:
    build: .
    ports:
      - 8000:8000
    environment:
     - DJANGO_APP=https://8772e80ccf48.ngrok.io
  build-proxy-port:
    image: nginx
    volumes:
     - ./nginx/django_nginx.conf.template:/etc/nginx/conf.d/django_nginx.conf.template
    ports:
     - "8001:8001"
    environment:
     - DJANGO_APP_URL=https://7a0e6326510d.ngrok.io
     - INBOUND_ROUTE=https://tntq8dnpdme.sandbox.verygoodproxy.com
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/django_nginx.conf.template > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf &&nginx -g 'daemon off;'"
